// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Button4;
void ui_event_Button7(lv_event_t * e);
lv_obj_t * ui_Button7;
void ui_event_Button8(lv_event_t * e);
lv_obj_t * ui_Button8;
void ui_event_Button10(lv_event_t * e);
lv_obj_t * ui_Button10;
void ui_event_Button12(lv_event_t * e);
lv_obj_t * ui_Button12;
void ui_event_Button15(lv_event_t * e);
lv_obj_t * ui_Button15;
void ui_event_Button16(lv_event_t * e);
lv_obj_t * ui_Button16;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Label1;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Chart1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label4;


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
lv_obj_t * ui_Label3;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Chart2;


// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
lv_obj_t * ui_Screen4;
lv_obj_t * ui_Chart3;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label7;


// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
lv_obj_t * ui_Screen5;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Chart4;
void ui_event_Button9(lv_event_t * e);
lv_obj_t * ui_Button9;
lv_obj_t * ui_Label9;


// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
lv_obj_t * ui_Screen6;
lv_obj_t * ui_Chart5;
lv_obj_t * ui_Label10;
void ui_event_Button11(lv_event_t * e);
lv_obj_t * ui_Button11;
lv_obj_t * ui_Label11;


// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
lv_obj_t * ui_Screen7;
lv_obj_t * ui_Chart6;
lv_obj_t * ui_Label12;
void ui_event_Button13(lv_event_t * e);
lv_obj_t * ui_Button13;
lv_obj_t * ui_Label13;


// SCREEN: ui_Screen8
void ui_Screen8_screen_init(void);
lv_obj_t * ui_Screen8;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Chart7;
void ui_event_Button14(lv_event_t * e);
lv_obj_t * ui_Button14;
lv_obj_t * ui_Label15;


// SCREEN: ui_Screen9
void ui_Screen9_screen_init(void);
lv_obj_t * ui_Screen9;
lv_obj_t * ui_Chart8;
lv_obj_t * ui_Label16;
void ui_event_Button17(lv_event_t * e);
lv_obj_t * ui_Button17;
lv_obj_t * ui_Label17;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_1605603976[1] = {&ui_img_2079358728};
const lv_img_dsc_t * ui_imgset_slide_[1] = {&ui_img_slide_1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
        _ui_screen_delete(&ui_Screen1);
    }
}
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
        _ui_screen_delete(&ui_Screen1);
        _ui_screen_delete(&ui_Screen2);
    }
}
void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen4_screen_init);
        _ui_screen_delete(&ui_Screen1);
        _ui_screen_delete(&ui_Screen2);
        _ui_screen_delete(&ui_Screen3);
    }
}
void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen5_screen_init);
        _ui_screen_delete(&ui_Screen1);
        _ui_screen_delete(&ui_Screen2);
        _ui_screen_delete(&ui_Screen3);
        _ui_screen_delete(&ui_Screen4);
    }
}
void ui_event_Button10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen6_screen_init);
        _ui_screen_delete(&ui_Screen1);
        _ui_screen_delete(&ui_Screen2);
        _ui_screen_delete(&ui_Screen3);
        _ui_screen_delete(&ui_Screen4);
        _ui_screen_delete(&ui_Screen5);
    }
}
void ui_event_Button12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen7, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen7_screen_init);
        _ui_screen_delete(&ui_Screen1);
        _ui_screen_delete(&ui_Screen2);
        _ui_screen_delete(&ui_Screen3);
        _ui_screen_delete(&ui_Screen4);
        _ui_screen_delete(&ui_Screen5);
        _ui_screen_delete(&ui_Screen6);
    }
}
void ui_event_Button15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen8_screen_init);
        _ui_screen_delete(&ui_Screen1);
        _ui_screen_delete(&ui_Screen2);
        _ui_screen_delete(&ui_Screen3);
        _ui_screen_delete(&ui_Screen4);
        _ui_screen_delete(&ui_Screen5);
        _ui_screen_delete(&ui_Screen6);
        _ui_screen_delete(&ui_Screen7);
    }
}
void ui_event_Button16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen9, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen9_screen_init);
        _ui_screen_delete(&ui_Screen1);
        _ui_screen_delete(&ui_Screen2);
        _ui_screen_delete(&ui_Screen3);
        _ui_screen_delete(&ui_Screen4);
        _ui_screen_delete(&ui_Screen5);
        _ui_screen_delete(&ui_Screen6);
        _ui_screen_delete(&ui_Screen7);
        _ui_screen_delete(&ui_Screen8);
    }
}
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
        _ui_screen_delete(&ui_Screen2);
    }
}
void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
        _ui_screen_delete(&ui_Screen3);
        _ui_screen_delete(&ui_Screen2);
    }
}
void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
        _ui_screen_delete(&ui_Screen2);
        _ui_screen_delete(&ui_Screen3);
        _ui_screen_delete(&ui_Screen4);
    }
}
void ui_event_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
        _ui_screen_delete(&ui_Screen5);
        _ui_screen_delete(&ui_Screen4);
        _ui_screen_delete(&ui_Screen3);
        _ui_screen_delete(&ui_Screen2);
    }
}
void ui_event_Button11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
        _ui_screen_delete(&ui_Screen6);
        _ui_screen_delete(&ui_Screen5);
        _ui_screen_delete(&ui_Screen4);
        _ui_screen_delete(&ui_Screen3);
        _ui_screen_delete(&ui_Screen2);
    }
}
void ui_event_Button13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
        _ui_screen_delete(&ui_Screen7);
        _ui_screen_delete(&ui_Screen6);
        _ui_screen_delete(&ui_Screen5);
        _ui_screen_delete(&ui_Screen4);
        _ui_screen_delete(&ui_Screen3);
        _ui_screen_delete(&ui_Screen2);
    }
}
void ui_event_Button14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
        _ui_screen_delete(&ui_Screen8);
        _ui_screen_delete(&ui_Screen7);
        _ui_screen_delete(&ui_Screen6);
        _ui_screen_delete(&ui_Screen5);
        _ui_screen_delete(&ui_Screen4);
        _ui_screen_delete(&ui_Screen3);
        _ui_screen_delete(&ui_Screen2);
    }
}
void ui_event_Button17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
        _ui_screen_delete(&ui_Screen2);
        _ui_screen_delete(&ui_Screen3);
        _ui_screen_delete(&ui_Screen4);
        _ui_screen_delete(&ui_Screen5);
        _ui_screen_delete(&ui_Screen6);
        _ui_screen_delete(&ui_Screen7);
        _ui_screen_delete(&ui_Screen8);
        _ui_screen_delete(&ui_Screen9);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui_Screen5_screen_init();
    ui_Screen6_screen_init();
    ui_Screen7_screen_init();
    ui_Screen8_screen_init();
    ui_Screen9_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
